# Generated by Django 5.1.2 on 2024-10-12 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='khatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('peroid', models.CharField(choices=[(1, '1 day'), (2, '2 day'), (3, '3 day'), (4, '4 day'), (5, '5 day'), (6, '6 day'), (7, 'week')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='khatmaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=7)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('khatma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='khatma.khatma')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='khatma',
            name='member',
            field=models.ManyToManyField(through='khatma.khatmaMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
