# Generated by Django 5.1.2 on 2024-11-12 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='khatmaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon', models.ImageField(upload_to='./khatmaGroupImages/<django.db.models.fields.CharField>_<built-in function id>')),
                ('description', models.CharField(default='BIO', max_length=290)),
            ],
        ),
        migrations.CreateModel(
            name='Khatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('endDate', models.DateTimeField()),
                ('intentions', models.CharField(default=None, max_length=180)),
                ('duaa', models.CharField(default=None, max_length=180)),
                ('startSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('startVerse', models.PositiveIntegerField(default=0)),
                ('endSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('endVerse', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('launcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launched_khatmas', to=settings.AUTH_USER_MODEL)),
                ('khatmaGroup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroup')),
            ],
            options={
                'unique_together': {('name', 'khatmaGroup')},
            },
        ),
        migrations.CreateModel(
            name='khatmaGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='admin', max_length=6)),
                ('khatmaGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatma_G_membership', to='khatma.khatmagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='khatmagroup',
            name='members',
            field=models.ManyToManyField(related_name='khatmaGroup', through='khatma.khatmaGroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='khatmaGroupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
                ('canAddMember', models.CharField(choices=[('all', 'all'), ('only_admins', 'only_admins'), ('custom', 'custom')], default='all', max_length=12)),
                ('canSendMessage', models.CharField(choices=[('all', 'all'), ('only_admins', 'only_admins'), ('custom', 'custom')], default='all', max_length=12)),
                ('All_can_launch_khatma', models.BooleanField(default=True)),
                ('canAddMember_custom', models.ManyToManyField(related_name='canAddMember', to=settings.AUTH_USER_MODEL)),
                ('canSendMessage_custom', models.ManyToManyField(related_name='canSendMessage', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='khatma.khatmagroup')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroupmembership')),
            ],
        ),
        migrations.CreateModel(
            name='khatmaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startShareSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('startShareVerse', models.PositiveIntegerField(default=0)),
                ('endShareSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('endShareVerse', models.PositiveIntegerField(default=0)),
                ('currentSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('currentVerse', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('finishDate', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('aborted', 'aborted')], default='ongoing', max_length=20)),
                ('khatma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='khatma.khatma')),
                ('khatmaGroupMembership', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroupmembership')),
            ],
            options={
                'unique_together': {('khatma', 'khatmaGroupMembership')},
            },
        ),
    ]
