# Generated by Django 5.1.2 on 2024-10-12 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatma',
            name='peroid',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], max_length=10),
        ),
        migrations.AlterField(
            model_name='khatmamembership',
            name='khatma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='khatma.khatma'),
        ),
        migrations.AlterField(
            model_name='khatmamembership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
