# Generated by Django 5.1.2 on 2024-10-29 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khatma',
            name='period',
        ),
        migrations.AddField(
            model_name='khatma',
            name='duaa',
            field=models.CharField(default='duaa', max_length=180),
        ),
        migrations.AddField(
            model_name='khatma',
            name='end_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='khatma',
            name='intentions',
            field=models.CharField(default='intentions', max_length=180),
        ),
        migrations.AddField(
            model_name='khatma',
            name='start_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='khatmagroup',
            name='bio',
            field=models.CharField(default='BIO', max_length=290),
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='endShareSurah',
            field=models.CharField(choices=[('the Cow', 'the Cow')], default='the Cow', max_length=35),
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='endShareVerse',
            field=models.IntegerField(default=280),
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='startShareSurah',
            field=models.CharField(choices=[('the Cow', 'the Cow')], default='the Cow', max_length=35),
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='startShareVerse',
            field=models.IntegerField(default=1),
        ),
    ]
