# Generated by Django 5.1.2 on 2024-11-15 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon', models.ImageField(upload_to='groupImages/')),
                ('description', models.CharField(default='BIO', max_length=290)),
            ],
        ),
        migrations.RemoveField(
            model_name='khatmagroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='khatmagroupmembership',
            name='khatmaGroup',
        ),
        migrations.RemoveField(
            model_name='khatmagroupmembership',
            name='user',
        ),
        migrations.AddField(
            model_name='khatma',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('aborted', 'aborted')], default='ongoing', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='khatma',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='khatma',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='khatma.group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.group'),
        ),
        migrations.AlterUniqueTogether(
            name='khatma',
            unique_together={('name', 'group')},
        ),
        migrations.CreateModel(
            name='groupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='admin', max_length=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='khatma.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupMembership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group', through='khatma.groupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='khatmamembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='groupMembership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='khatmaMembership', to='khatma.groupmembership'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.groupmembership'),
        ),
        migrations.AlterUniqueTogether(
            name='khatmamembership',
            unique_together={('khatma', 'groupMembership')},
        ),
        migrations.CreateModel(
            name='groupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canAddMember', models.CharField(choices=[('all', 'all'), ('only_admins', 'only_admins'), ('custom', 'custom')], default='all', max_length=12)),
                ('canSendMessage', models.CharField(choices=[('all', 'all'), ('only_admins', 'only_admins'), ('custom', 'custom')], default='all', max_length=12)),
                ('All_can_launch_khatma', models.BooleanField(default=True)),
                ('canAddMember_custom', models.ManyToManyField(related_name='canAddMember', to=settings.AUTH_USER_MODEL)),
                ('canSendMessage_custom', models.ManyToManyField(related_name='canSendMessage', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='khatma.group')),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='groupMedia/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='khatma.group')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='khatma.groupmembership')),
            ],
        ),
        migrations.DeleteModel(
            name='khatmaGroupSettings',
        ),
        migrations.RemoveField(
            model_name='khatma',
            name='khatmaGroup',
        ),
        migrations.RemoveField(
            model_name='khatmamembership',
            name='khatmaGroupMembership',
        ),
        migrations.DeleteModel(
            name='khatmaGroup',
        ),
        migrations.DeleteModel(
            name='khatmaGroupMembership',
        ),
    ]
