# Generated by Django 5.1.2 on 2024-11-11 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='khatmaGroupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canAddMember', models.CharField(choices=[('all', 'all'), ('only_admins', 'only_admins'), ('custom', 'custom')], default='all', max_length=12)),
                ('canSendMessage', models.CharField(choices=[('all', 'all'), ('only_admins', 'only_admins'), ('custom', 'custom')], default='all', max_length=12)),
                ('All_can_suggest_khatma', models.BooleanField(default=True)),
                ('canAddMember_custom', models.ManyToManyField(related_name='canAddMember', to=settings.AUTH_USER_MODEL)),
                ('canSendMessage_custom', models.ManyToManyField(related_name='canSendMessage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=400000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='hizbsList',
        ),
        migrations.DeleteModel(
            name='thomonList',
        ),
        migrations.RemoveField(
            model_name='khatma',
            name='period',
        ),
        migrations.AddField(
            model_name='khatma',
            name='duaa',
            field=models.CharField(default=None, max_length=180),
        ),
        migrations.AddField(
            model_name='khatma',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khatma',
            name='intentions',
            field=models.CharField(default=None, max_length=180),
        ),
        migrations.AddField(
            model_name='khatma',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khatmagroup',
            name='description',
            field=models.CharField(default='BIO', max_length=290),
        ),
        migrations.AddField(
            model_name='khatmagroup',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khatmagroupmembership',
            name='since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='endShareSurah',
            field=models.CharField(choices=[('the Cow', 'the Cow')], default='the Cow', max_length=35),
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='endShareVerse',
            field=models.IntegerField(default=280),
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='startShareSurah',
            field=models.CharField(choices=[('the Cow', 'the Cow')], default='the Cow', max_length=35),
        ),
        migrations.AddField(
            model_name='khatmamembership',
            name='startShareVerse',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='khatmagroup',
            name='icon',
            field=models.ImageField(upload_to='./khatmaGroupImage/<django.db.models.fields.CharField>_<built-in function id>'),
        ),
        migrations.AlterField(
            model_name='khatmagroup',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='khatmagroupsettings',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='khatma.khatmagroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroupmembership'),
        ),
    ]
