# Generated by Django 5.1.2 on 2024-10-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0002_alter_khatma_peroid_alter_khatmamembership_khatma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatma',
            name='peroid',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], max_length=10),
        ),
    ]
