# Generated by Django 5.1.2 on 2024-10-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0003_alter_khatma_duaa_alter_khatma_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatmagroup',
            name='icon',
            field=models.ImageField(upload_to='./<django.db.models.fields.CharField>/KGImg'),
        ),
    ]
