# Generated by Django 5.1.2 on 2024-11-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0004_alter_khatmagroup_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hizbsList',
        ),
        migrations.DeleteModel(
            name='thomonList',
        ),
    ]
