# Generated by Django 5.1.2 on 2024-10-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0004_alter_khatma_peroid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khatma',
            old_name='peroid',
            new_name='period',
        ),
    ]
