# Generated by Django 5.1.2 on 2024-11-04 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0005_delete_hizbslist_delete_thomonlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatmagroupmembership',
            name='since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
