# Generated by Django 5.1.2 on 2024-10-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0005_rename_peroid_khatma_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatma',
            name='period',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default=None, max_length=10),
        ),
    ]
