# Generated by Django 5.1.2 on 2024-11-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0006_khatmagroupmembership_since'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khatma',
            old_name='end_Date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='khatma',
            old_name='start_Date',
            new_name='startDate',
        ),
    ]
