services:
  django-app:
    build: 
      context: ./app
    container_name: django-app
    env_file:
      - ./env_vars_django.txt
    ports:
      - "8000:8000"
    volumes:
      - ./backend_static:/app/static
      - ./media:/app/files
      - ./app:/app
    depends_on:
      - db
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  
  flower:
    container_name: flower
    image: mher/flower
    ports:
      - "5555:5555"
    command: celery -A  flower
    env_file:
      - ./env_vars_flower.txt
    
    depends_on:
      - celery
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  
  db:
    image: postgres:13
    container_name: database
    env_file:
      - ./env_vars_db.txt
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  celery:
    container_name: celery
    restart: always
    build:
      context: ./app
    command: celery -A khatamat_b worker -l INFO -B
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./env_vars_django.txt
    depends_on:
      - django-app
      - redis

volumes:
  postgres_data:
  backend_static:
  media:
    external: true
