# Generated by Django 5.1.2 on 2024-12-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon', models.ImageField(upload_to='groupImages/')),
                ('description', models.CharField(default='BIO', max_length=290)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='groupMedia/')),
            ],
        ),
        migrations.CreateModel(
            name='groupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='admin', max_length=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='khatma.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupMembership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group', through='khatma.groupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='groupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canAddMember', models.CharField(choices=[('all', 'all'), ('only_admins', 'only_admins'), ('custom', 'custom')], default='all', max_length=12)),
                ('canSendMessage', models.CharField(choices=[('all', 'all'), ('only_admins', 'only_admins'), ('custom', 'custom')], default='all', max_length=12)),
                ('All_can_launch_khatma', models.BooleanField(default=True)),
                ('canAddMember_custom', models.ManyToManyField(related_name='canAddMember', to=settings.AUTH_USER_MODEL)),
                ('canSendMessage_custom', models.ManyToManyField(related_name='canSendMessage', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='khatma.group')),
            ],
        ),
        migrations.CreateModel(
            name='Khatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('endDate', models.DateTimeField()),
                ('intentions', models.CharField(default=None, max_length=180)),
                ('duaa', models.CharField(default=None, max_length=180)),
                ('startSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('startVerse', models.PositiveIntegerField(default=0)),
                ('endSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('endVerse', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('aborted', 'aborted')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='khatma.group')),
                ('launcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launched_khatmas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='khatmaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startShareSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('startShareVerse', models.PositiveIntegerField(default=0)),
                ('endShareSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('endShareVerse', models.PositiveIntegerField(default=0)),
                ('currentSurah', models.CharField(choices=[('the cow', 'the cow')], max_length=35)),
                ('currentVerse', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('finishDate', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('aborted', 'aborted')], default='ongoing', max_length=20)),
                ('groupMembership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatmaMembership', to='khatma.groupmembership')),
                ('khatma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='khatma.khatma')),
            ],
            options={
                'unique_together': {('khatma', 'groupMembership')},
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('file_path', models.FilePathField(blank=True, null=True, path='/app/files/groupMedia')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='khatma.media')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='khatma.group')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='khatma.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentMessages', to='khatma.groupmembership')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'created_at'], name='khatma_mess_group_i_ba79fa_idx'), models.Index(fields=['sender'], name='khatma_mess_sender__fa79d3_idx')],
            },
        ),
    ]
