# Generated by Django 5.1.2 on 2024-10-29 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khatma', '0003_alter_khatma_duaa_alter_khatma_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('join request', 'join request')], max_length=100)),
                ('message', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread')], max_length=10)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('Kh', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='khatma.khatma')),
                ('kh_G', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='khatma.khatmagroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='joinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('khatmaGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JoinRequest_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'khatmaGroup', 'owner')},
            },
        ),
    ]
