# Generated by Django 5.1.2 on 2024-11-03 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0004_alter_community_picture_alter_post_photo_and_more'),
        ('khatma', '0005_delete_hizbslist_delete_thomonlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='messageN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('khatmaGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='postN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='brothershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_brothership_req', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('brother', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='joinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('khatmaGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khatma.khatmagroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_join_req', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'khatmaGroup', 'owner')},
            },
        ),
    ]
