# Generated by Django 5.1.2 on 2024-11-01 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_join_req', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='brothershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread')], default='unread', max_length=10)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('brother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_brothership_req', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
