# Generated by Django 5.1.2 on 2024-11-03 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0005_delete_hizbslist_delete_thomonlist'),
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='brothershiprequest',
            old_name='brother',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='brothershiprequest',
            old_name='owner',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='joinrequest',
            old_name='user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='joinrequest',
            old_name='owner',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='messagen',
            old_name='owner',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='postn',
            old_name='owner',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='brothershiprequest',
            unique_together={('receiver', 'sender')},
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('receiver', 'khatmaGroup', 'sender')},
        ),
    ]
