# Generated by Django 5.1.2 on 2024-11-04 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_brother_brothershiprequest_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='acceptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acceptor_joinRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
