# Generated by Django 5.1.2 on 2024-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_brothershiprequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brothershiprequest',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='messagen',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='unread', max_length=10),
        ),
        migrations.AlterField(
            model_name='postn',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='unread', max_length=10),
        ),
    ]
