# Generated by Django 5.0.6 on 2024-07-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(choices=[('Algeria', 'DZ')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], default=None, max_length=7),
        ),
    ]
