# Generated by Django 5.0.6 on 2024-07-03 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_country_alter_myuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 18, 10, 7, 320508, tzinfo=datetime.timezone.utc)),
        ),
    ]
