# Generated by Django 5.1.2 on 2024-10-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Kh',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='kh_G',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='joinRequest',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
