# Generated by Django 5.1.2 on 2024-10-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_notification_kh_remove_notification_kh_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profileBan',
            field=models.ImageField(default=None, null=True, upload_to='./<django.db.models.fields.CharField>/profileBan'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profilePic',
            field=models.ImageField(default=None, null=True, upload_to='./<django.db.models.fields.CharField>/profilePic'),
        ),
    ]
