# Generated by Django 5.0.6 on 2024-07-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_myuser_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part1', models.CharField(max_length=20)),
                ('part2', models.CharField(max_length=20)),
                ('part3', models.CharField(max_length=20)),
                ('part4', models.CharField(max_length=20)),
                ('part5', models.CharField(max_length=20)),
                ('part6', models.CharField(max_length=20)),
                ('part7', models.CharField(max_length=20)),
                ('part8', models.CharField(max_length=20)),
                ('part9', models.CharField(max_length=20)),
                ('part10', models.CharField(max_length=20)),
                ('part11', models.CharField(max_length=20)),
                ('part12', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
