# Generated by Django 5.1.2 on 2024-11-01 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_myuser_profileban_myuser_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='profileBan',
        ),
        migrations.AddField(
            model_name='myuser',
            name='brothersNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='khatmasNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profilePic',
            field=models.ImageField(default='<django.db.models.fields.CharField>/profilePic/default.png', null=True, upload_to='./<django.db.models.fields.CharField>/profilePic'),
        ),
        migrations.CreateModel(
            name='brothership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brother', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='brothers',
            field=models.ManyToManyField(through='api.brothership', to=settings.AUTH_USER_MODEL),
        ),
    ]
