# Generated by Django 5.0.6 on 2024-07-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
