# Generated by Django 5.1.2 on 2024-11-01 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_myuser_profileban_myuser_brothersnum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brothership',
            options={'verbose_name': 'Brothership'},
        ),
        migrations.AlterField(
            model_name='brothership',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brothership_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brothership',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brothership_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
