# Generated by Django 5.1.2 on 2024-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_brothership_options_alter_brothership_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fullname',
            field=models.CharField(default='moussa mousselmal', max_length=30),
        ),
    ]
