# Generated by Django 5.0.6 on 2024-07-06 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_part1_part_part01_remove_part_part2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL),
        ),
    ]
