# Generated by Django 5.1.2 on 2024-11-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_myuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
