# Generated by Django 5.0.6 on 2024-08-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_khatma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatma',
            name='num_days',
            field=models.IntegerField(choices=[('1 day', 1), ('2 day', 2), ('3 day', 3), ('4 day', 4), ('5 day', 5), ('6 day', 6), ('week', 7)], default=None, max_length=20),
        ),
    ]
