# Generated by Django 5.1.2 on 2024-11-02 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_myuser_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='brothers',
            field=models.ManyToManyField(related_name='brothers_set', through='api.brothership', to=settings.AUTH_USER_MODEL),
        ),
    ]
