# Generated by Django 5.1.2 on 2024-11-04 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_myuser_brothers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='blocked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
