# Generated by Django 5.0.6 on 2024-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_khatma_num_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatma',
            name='num_days',
            field=models.IntegerField(choices=[(1, '1 day'), (2, '2 day'), (3, '3 day'), (4, '4 day'), (5, '5 day'), (6, '6 day'), (7, 'week')], default=None),
        ),
    ]
