# Generated by Django 5.1.2 on 2024-11-04 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_myuser_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='blocked',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
