# Generated by Django 5.1.2 on 2024-10-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_khatma_num_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='user',
        ),
        migrations.DeleteModel(
            name='Khatma',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
