# Generated by Django 5.1.2 on 2024-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='picture',
            field=models.ImageField(null=True, upload_to='communityIMG/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='community',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
