# Generated by Django 5.1.2 on 2024-10-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_picture_alter_community_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
