# Generated by Django 5.1.2 on 2024-11-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_picture_alter_post_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='postPic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(upload_to='postVid'),
        ),
    ]
