# Generated by Django 5.1.2 on 2024-12-18 10:12

import django.contrib.auth.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='brothership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother_since', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Brothership',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('male', 'M'), ('female', 'F')], default=None, max_length=7, null=True)),
                ('country', models.CharField(choices=[('Algeria', 'DZ')], default=None, max_length=20, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('khatmasNum', models.IntegerField(default=0)),
                ('brothersNum', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profilePic', models.ImageField(default='UserProfilePic/default.png', upload_to='UserPofilePic')),
                ('is_staff', models.BooleanField(default=False)),
                ('blocked', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('muted_brothers', models.ManyToManyField(default=None, related_name='muting_brothers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
