# Generated by Django 5.1.2 on 2024-12-18 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='muted_groups',
            field=models.ManyToManyField(default=None, related_name='muting_members', to='group.group'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='brothership',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brothership_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brothership',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brothership_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='brothers',
            field=models.ManyToManyField(related_name='brothers_set', through='api.brothership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='brothership',
            unique_together={('user1', 'user2')},
        ),
    ]
