# Generated by Django 5.1.2 on 2024-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profilePic',
            field=models.ImageField(default='UserProfilePic/default.png', upload_to='UserPofilePic'),
        ),
    ]
