# Generated by Django 5.1.2 on 2024-12-10 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='brothers',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='brothersNum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='khatmasNum',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='private',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('male', 'M'), ('female', 'F')], default=None, max_length=7)),
                ('country', models.CharField(choices=[('Algeria', 'DZ')], default=None, max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('khatmasNum', models.IntegerField(default=0)),
                ('brothersNum', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('blocked', models.ManyToManyField(default=None, to='api.usersetting')),
                ('brothers', models.ManyToManyField(related_name='brothers_set', through='api.brothership', to='api.usersetting')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
