# Generated by Django 5.1.2 on 2024-11-17 20:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_profilepic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(choices=[('Algeria', 'DZ')], default='DZ', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], default='M', max_length=7),
        ),
    ]
