# Generated by Django 5.1.2 on 2024-12-10 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_myuser_blocked_remove_myuser_brothers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='brothers',
        ),
        migrations.AddField(
            model_name='myuser',
            name='blocked',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='brothers',
            field=models.ManyToManyField(related_name='brothers_set', through='api.brothership', to=settings.AUTH_USER_MODEL),
        ),
    ]
