# Generated by Django 5.1.2 on 2024-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usersetting_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='mode',
            field=models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=20),
        ),
    ]
