# Generated by Django 5.1.2 on 2024-12-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usersetting_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='country',
            field=models.CharField(choices=[('Algeria', 'DZ')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], default=None, max_length=7, null=True),
        ),
    ]
