# Generated by Django 5.1.2 on 2024-12-11 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usersetting_country_alter_usersetting_gender'),
        ('khatma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='muted_brothers',
            field=models.ManyToManyField(default=None, related_name='muting_brothers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='muted_groups',
            field=models.ManyToManyField(default=None, related_name='muting_members', to='khatma.group'),
        ),
    ]
