# Generated by Django 5.1.2 on 2024-11-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_post_photo_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='authentications',
            field=models.CharField(choices=[('none', 'none'), ('custom', 'custom')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='community.community'),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=10),
        ),
    ]
